name: Build
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            suffix: ''
          - os: windows-latest
            suffix: .exe
          - os: macos-latest
            suffix: ''
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
      - run: cargo build --bin northstar-rcon-cli --release
      - uses: actions/upload-artifact@v3
        with:
          name: northstar-rcon-cli-${{ matrix.os }}
          path: target/release/northstar-rcon-cli${{ matrix.suffix }}
